### ISSUE TITLE
Internal Server Error when using BayestarWebQuery

### ISSUE THREAD

**Issue by amaliestokholm** [gregreen/dustmaps#42]
When I run the example for how to use BayestarWebQuery from http://argonaut.skymaps.info/usage, it crashes with `500 Internal Server Error`. 

Here is what I did:
```
$ python3 -m venv myvenv
$ source myvenv/bin/activate
(myvenv) $ pip install dustmaps
Collecting dustmaps
Using cached dustmaps-1.0.10-py3-none-any.whl (450 kB)
...
Successfully installed PyYAML-6.0 astropy-5.2.2 certifi-2022.12.7 charset-normalizer-3.1.0 contourpy-1.0.7 cycler-0.11.0 dustmaps-1.0.10 fonttools-4.39.3 h5py-3.8.0 healpy-1.16.2 idna-3.4 kiwisolver-1.4.4 matplotlib-3.7.1 numpy-1.24.2 packaging-23.0 pillow-9.5.0 progressbar2-4.2.0 pyerfa-2.0.0.3 pyparsing-3.0.9 python-dateutil-2.8.2 python-utils-3.5.2 requests-2.28.2 scipy-1.10.1 six-1.16.0 urllib3-1.26.15
(myvenv) $ python3 dustmapsexample.py
Response received from server:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

Traceback (most recent call last):
File "dustmapsexample.py", line 9, in <module>
    reddening = bayestar(coords, mode='random_sample')
  File "myvenv/lib/python3.10/site-packages/dustmaps/map_base.py", line 112, in _wrapper_func
    return f(self, coords, **kwargs)
  File "myvenv/lib/python3.10/site-packages/dustmaps/map_base.py", line 512, in __call__
    return self.query(coords, **kwargs)
  File "myvenv/lib/python3.10/site-packages/dustmaps/map_base.py", line 112, in _wrapper_func
    return f(self, coords, **kwargs)
  File "myvenv/lib/python3.10/site-packages/dustmaps/map_base.py", line 359, in api_wrapper
    raise err
  File "myvenv/lib/python3.10/site-packages/dustmaps/map_base.py", line 355, in api_wrapper
    r.raise_for_status()
  File "myvenv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://argonaut.skymaps.info/api/v2/bayestar2017/query
(myvenv) $ cat dustmapsexample.py
from astropy.coordinates import SkyCoord
import astropy.units as units
from dustmaps.bayestar import BayestarWebQuery

bayestar = BayestarWebQuery(version='bayestar2017')
coords = SkyCoord(90.*units.deg, 30.*units.deg,
                  distance=100.*units.pc, frame='galactic')

reddening = bayestar(coords, mode='random_sample')
print(reddening)
```

**Comment by gregreen** [comment]
Thank you for letting me know about this problem. This is is actually a problem with the server, rather than the `dustmaps` package itself. I have now fixed the issue with the server, so `BayestarWebQuery` should be working again.

In case this problem pops up again, however, you can always switch from `BayestarWebQuery` to `BayestarQuery`, the latter of which loads the data file locally. The code is identical, except for the change from `BayestarWebQuery` to  `BayestarQuery`.
